// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIT385bPUe44acsXBE71Jxe0rr0tCZBzE',
    appId: '1:104319421446:web:6e17aae8d42fdbdf088787',
    messagingSenderId: '104319421446',
    projectId: 'alfa7-fddee',
    authDomain: 'alfa7-fddee.firebaseapp.com',
    storageBucket: 'alfa7-fddee.firebasestorage.app',
    measurementId: 'G-PJN79PWQN8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIT385bPUe44acsXBE71Jxe0rr0tCZBzE',
    appId: '1:104319421446:web:2e8b599915a92a2f088787',
    messagingSenderId: '104319421446',
    projectId: 'alfa7-fddee',
    authDomain: 'alfa7-fddee.firebaseapp.com',
    storageBucket: 'alfa7-fddee.firebasestorage.app',
    measurementId: 'G-6HY1JT1MGY',
  );
}
