// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVxlS3v43b1wfFpMPJp8IKiPMdzs4_Fdg',
    appId: '1:883588472994:web:6421ec616b0afeb90677fb',
    messagingSenderId: '883588472994',
    projectId: 'money-transfer-23db8',
    authDomain: 'money-transfer-23db8.firebaseapp.com',
    storageBucket: 'money-transfer-23db8.firebasestorage.app',
    measurementId: 'G-ZVPVXJRNK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU8tqIGgK6BKCtnLKvGp3Qn7Btf14qDws',
    appId: '1:883588472994:android:5e30f9bced12a62f0677fb',
    messagingSenderId: '883588472994',
    projectId: 'money-transfer-23db8',
    storageBucket: 'money-transfer-23db8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1EiRe4AarEnfQ3l-rF3tWc0n0FJ9s6s8',
    appId: '1:883588472994:ios:cce9e9570b9e238c0677fb',
    messagingSenderId: '883588472994',
    projectId: 'money-transfer-23db8',
    storageBucket: 'money-transfer-23db8.firebasestorage.app',
    iosClientId: '883588472994-b0kn6ovn7sjhco1qfidnrujl5hmmt3ad.apps.googleusercontent.com',
    iosBundleId: 'com.example.alfaDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1EiRe4AarEnfQ3l-rF3tWc0n0FJ9s6s8',
    appId: '1:883588472994:ios:cce9e9570b9e238c0677fb',
    messagingSenderId: '883588472994',
    projectId: 'money-transfer-23db8',
    storageBucket: 'money-transfer-23db8.firebasestorage.app',
    iosClientId: '883588472994-b0kn6ovn7sjhco1qfidnrujl5hmmt3ad.apps.googleusercontent.com',
    iosBundleId: 'com.example.alfaDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVxlS3v43b1wfFpMPJp8IKiPMdzs4_Fdg',
    appId: '1:883588472994:web:df67bb5ecbc5e3080677fb',
    messagingSenderId: '883588472994',
    projectId: 'money-transfer-23db8',
    authDomain: 'money-transfer-23db8.firebaseapp.com',
    storageBucket: 'money-transfer-23db8.firebasestorage.app',
    measurementId: 'G-DHTW2BQPH5',
  );
}
